<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Barang;
use Carbon\Carbon;

class BarangSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();

        $barangs = [
            // Laptop (Kategori: 1)
            [
                'kode_barang' => 'BRG001',
                'nama_barang' => 'Laptop Dell Inspiron',
                'merek' => 'Dell',
                'model_seri' => 'Inspiron 15',
                'kategori_id' => 1,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Laptop i5, RAM 8GB',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG002',
                'nama_barang' => 'Laptop Asus ROG',
                'merek' => 'Asus',
                'model_seri' => 'ROG Strix',
                'kategori_id' => 1,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Laptop gaming high-end',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Aksesoris Komputer (Kategori: 2)
            [
                'kode_barang' => 'BRG003',
                'nama_barang' => 'Mouse Logitech G102',
                'merek' => 'Logitech',
                'model_seri' => 'G102',
                'kategori_id' => 2,
                'status' => 'Tersedia',
                'kondisi' => 'Lecet',
                'keterangan' => 'Mouse gaming dengan DPI 8000',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG004',
                'nama_barang' => 'Keyboard Mechanical',
                'merek' => 'SteelSeries',
                'model_seri' => 'Apex Pro',
                'kategori_id' => 2,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Keyboard RGB dengan switch red',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Monitor & Display (Kategori: 3)
            [
                'kode_barang' => 'BRG005',
                'nama_barang' => 'Monitor LG 24 Inch',
                'merek' => 'LG',
                'model_seri' => '24MK600',
                'kategori_id' => 3,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Monitor IPS resolusi 1080p',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG006',
                'nama_barang' => 'Proyektor BenQ',
                'merek' => 'BenQ',
                'model_seri' => 'HT3550',
                'kategori_id' => 3,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Proyektor 4K untuk presentasi',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Printer & Scanner (Kategori: 4)
            [
                'kode_barang' => 'BRG007',
                'nama_barang' => 'Printer Epson L3150',
                'merek' => 'Epson',
                'model_seri' => 'L3150',
                'kategori_id' => 4,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Printer All-in-One dengan WiFi',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG008',
                'nama_barang' => 'Scanner Canon CanoScan',
                'merek' => 'Canon',
                'model_seri' => 'CanoScan LiDE 300',
                'kategori_id' => 4,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Scanner flatbed dengan resolusi tinggi',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Jaringan & Komunikasi (Kategori: 5)
            [
                'kode_barang' => 'BRG009',
                'nama_barang' => 'Router TP-Link Archer',
                'merek' => 'TP-Link',
                'model_seri' => 'Archer C7',
                'kategori_id' => 5,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Router dual-band dengan kecepatan tinggi',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG010',
                'nama_barang' => 'Switch Cisco 8 Port',
                'merek' => 'Cisco',
                'model_seri' => 'SG110-08',
                'kategori_id' => 5,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Switch unmanaged untuk jaringan kecil',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Perangkat Penyimpanan (Kategori: 6)
            [
                'kode_barang' => 'BRG011',
                'nama_barang' => 'SSD Samsung 1TB',
                'merek' => 'Samsung',
                'model_seri' => '870 QVO',
                'kategori_id' => 6,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'SSD SATA III dengan kapasitas 1TB',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG012',
                'nama_barang' => 'External HDD Seagate 2TB',
                'merek' => 'Seagate',
                'model_seri' => 'Backup Plus',
                'kategori_id' => 6,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'HDD eksternal portabel dengan USB 3.0',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Tambahan data manual hingga 30 barang
            [
                'kode_barang' => 'BRG013',
                'nama_barang' => 'Laptop Lenovo ThinkPad',
                'merek' => 'Lenovo',
                'model_seri' => 'ThinkPad X1 Carbon',
                'kategori_id' => 1,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Laptop bisnis ringan dan tangguh',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG014',
                'nama_barang' => 'Mouse Wireless Microsoft',
                'merek' => 'Microsoft',
                'model_seri' => 'Wireless Mobile Mouse 1850',
                'kategori_id' => 2,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Mouse wireless ergonomis',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG015',
                'nama_barang' => 'Monitor Samsung 27 Inch',
                'merek' => 'Samsung',
                'model_seri' => 'S27F350',
                'kategori_id' => 3,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Monitor LED dengan desain bezel tipis',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG016',
                'nama_barang' => 'Printer HP LaserJet',
                'merek' => 'HP',
                'model_seri' => 'LaserJet Pro MFP',
                'kategori_id' => 4,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Printer laser untuk kantor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG017',
                'nama_barang' => 'Access Point Ubiquiti',
                'merek' => 'Ubiquiti',
                'model_seri' => 'UniFi AP AC Lite',
                'kategori_id' => 5,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Access Point untuk jaringan Wi-Fi',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG018',
                'nama_barang' => 'SSD NVMe Kingston 500GB',
                'merek' => 'Kingston',
                'model_seri' => 'A2000',
                'kategori_id' => 6,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'SSD NVMe dengan kecepatan tinggi',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG019',
                'nama_barang' => 'Laptop Acer Swift 3',
                'merek' => 'Acer',
                'model_seri' => 'Swift 3 SF314',
                'kategori_id' => 1,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Laptop ultrabook dengan layar IPS',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG020',
                'nama_barang' => 'Headset Gaming Razer',
                'merek' => 'Razer',
                'model_seri' => 'Kraken X',
                'kategori_id' => 2,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Headset gaming dengan surround sound',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG021',
                'nama_barang' => 'Monitor Curved Samsung',
                'merek' => 'Samsung',
                'model_seri' => 'C27F390',
                'kategori_id' => 3,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Monitor curved 27 inch',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG022',
                'nama_barang' => 'Printer Canon Pixma',
                'merek' => 'Canon',
                'model_seri' => 'Pixma MG2570',
                'kategori_id' => 4,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Printer inkjet untuk kebutuhan sehari-hari',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG023',
                'nama_barang' => 'Switch TP-Link 16 Port',
                'merek' => 'TP-Link',
                'model_seri' => 'TL-SG1016D',
                'kategori_id' => 5,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Switch unmanaged untuk jaringan menengah',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG024',
                'nama_barang' => 'External SSD SanDisk 500GB',
                'merek' => 'SanDisk',
                'model_seri' => 'Extreme Portable SSD',
                'kategori_id' => 6,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'SSD eksternal tahan air dan debu',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG025',
                'nama_barang' => 'Laptop HP Pavilion',
                'merek' => 'HP',
                'model_seri' => 'Pavilion 15',
                'kategori_id' => 1,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Laptop multimedia dengan layar touchscreen',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG026',
                'nama_barang' => 'Webcam Logitech C920',
                'merek' => 'Logitech',
                'model_seri' => 'C920',
                'kategori_id' => 2,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Webcam HD untuk streaming dan meeting',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG027',
                'nama_barang' => 'Monitor Gaming ASUS',
                'merek' => 'ASUS',
                'model_seri' => 'VG248QG',
                'kategori_id' => 3,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Monitor gaming 144Hz',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG028',
                'nama_barang' => 'Printer Brother HL-L2320D',
                'merek' => 'Brother',
                'model_seri' => 'HL-L2320D',
                'kategori_id' => 4,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Printer laser monokrom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG029',
                'nama_barang' => 'Router MikroTik',
                'merek' => 'MikroTik',
                'model_seri' => 'hAP ac2',
                'kategori_id' => 5,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Router untuk jaringan rumahan dan kecil',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_barang' => 'BRG030',
                'nama_barang' => 'Flashdisk SanDisk 128GB',
                'merek' => 'SanDisk',
                'model_seri' => 'Ultra Flair',
                'kategori_id' => 6,
                'status' => 'Tersedia',
                'kondisi' => 'Baik',
                'keterangan' => 'Flashdisk USB 3.0 dengan kecepatan tinggi',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Insert data ke database
        Barang::insert($barangs);
    }
}